import { Inter } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/pagetransition";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 //Had to minus the height of the navigation bar from the total page height to give the height foir the rest of the page
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageTransition>
            { children }
        </PageTransition>
        </body>
    </html>
  );
}
